### ISSUE TITLE
Command line validator does not execute, could not find or load main class edu.iris.dmc.Application

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#10]
I downloaded the (1.5.2 jar)[https://github.com/iris-edu/StationXML-Validator/releases/download/v1.5.2/StationXml-validator--1.5.2.jar) and it does not run:

> $ java -jar StationXml-validator--1.5.2.jar 
Error: Could not find or load main class edu.iris.dmc.Application

**Comment by yazan-iris** [comment]
Fixed it, maven config was incorrectly run.
