### ISSUE TITLE
Add Rule: Error: 423

### ISSUE THREAD

**Issue by timronan** [iris-edu/stationxml-validator#101]
Add Rule: Error: 423: If Decimation and StageGain are included in a stage then PolesZeros or Coefficients or ResponseList or FIR must also be included. 

We are proposing to add the rule listed above. Please comment with any feedback.

**Comment by timronan** [comment]
If Stage[N]:Decimation and Stage[N]:StageGain are included then Stage[N]:PolesZeros or Stage[N]:Coefficients or Stage[N]:ResponseList or Stage[N]:FIR must also be included.

**Comment by metempleton** [comment]
That sounds ok to me.

**Comment by timronan** [comment]
Rule 423 was added by commit 93638a5b5cc3660fd88781e8459bb561c1a5b588.
