### ISSUE TITLE
Add Rules 417 and 418 which enforce sequential indexing for poles and zeros.

### ISSUE THREAD

**Issue by timronan** [iris-edu/stationxml-validator#102]
Error: 417
IF Stage[N]:PolesZeros contains Zeros then Zero:Number must start at 0 and be sequential. 

Error: 418
IF Stage[N]:PolesZeros  contains Poles then Pole:Number must start at 0 and be sequential. 

We are proposing to add the rule listed above. Please comment with any feedback.

**Comment by timronan** [comment]
Rules 417 and 418 were combined into rule:

417: If Stage[N]:PolesZeros contains Zeros and Poles then Zero:Number and Pole:Number must start at 0 and be sequential.

This rule has been included by commit 93638a5b5cc3660fd88781e8459bb561c1a5b588.

**Comment by SCEDC** [comment]
We would like to request this rule not be implemented in the validator. (on behalf of SIS development team)

First of all, the order of poles and zeros does not matter when calculating the response of a channel.

Secondly, the number attribute in FDSN StationXML is optional.
