### ISSUE TITLE
Make code usable as a java library

### ISSUE THREAD

**Issue by bentatham** [iris-edu/stationxml-validator#104]
Currently, the code is written to be used solely as a command line utility. If the classes/methods were declared a bit differently, this library could be more easily integrated into other products either as test code or even as runtime checking before creating/downloading StationXML, even from vendor products.

The goal would be to keep the public interface the same, especially with no changes to the command line interface. Minimal changes to expose methods (non-private) and make instantiation easier (less static variables, etc).

I am happy to contribute a Pull Request to make these changes.

**Comment by timronan** [comment]
Hi @bentatham,

We are happy that you have taken interest in the stationxml-validator and are open to code modifications as pull request. Please follow the guidelines described in the "[Contributing to the StationXML Validator](http://iris-edu.github.io/stationxml-validator/contribution.html)" documentation. @yazan-iris or myself will be code reviewers. Let [me](https://www.iris.edu/hq/staff/employee/ronan) know if you have any questions.
