### ISSUE TITLE
documentation is outdated? --format option

### ISSUE THREAD

**Issue by jrhartog** [iris-edu/stationxml-validator#108]
`--format report` this option does not exist in version 1.7.0-RC-03

> [2020-05-08 15:55:48] [SEVERE] edu.iris.dmc.Application main: File --format does not exist!edu.iris.dmc.CommandLine.parse(CommandLine.java:203)
> edu.iris.dmc.Application.main(Application.java:87)

wiki has this example:
`java -jar station-xml-validator-1.5.9.3.jar IU.ANMO.00.BHZ.xml --format report`

**Comment by timronan** [comment]
Page has been updated thanks for reporting.

**Comment by timronan** [comment]
Has this been resolved?
