### ISSUE TITLE
Which Args are allowed together is confusing

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-validator#109]
This works:
`java -jar stationxml-validator-1.7.0-RC-03.jar --units`
but this fails with a confusing error message:
`java -jar stationxml-validator-1.7.0-RC-03.jar  --units CO_ADSC.xml.1 `

```
[2020-05-13 11:13:34] [SEVERE] edu.iris.dmc.Application main: File --units does not exist!edu.iris.dmc.CommandLine.parse(CommandLine.java:203)
edu.iris.dmc.Application.main(Application.java:87)
```

**Comment by timronan** [comment]
This issue is addressed by commit 50dcce5 and can be tested using stationxml-validator-1.7.0-RC-04-SNAPSHOT. Please download the release and test. If multiple arguments are given for either --units or --rules the output message reads: 
```
 [SEVERE] edu.iris.dmc.Application main: --units must be the only input argument. edu.iris.dmc.CommandLine.parse(CommandLine.java:177)
```
or
```
 [SEVERE] edu.iris.dmc.Application main: --rules must be the only input argument. edu.iris.dmc.CommandLine.parse(CommandLine.java:177)
```
