### ISSUE TITLE
Rules table has some strange characters, incomplete and misspelled entries

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#11]
Using 1.5.2 with the --print-rules option the resulting table has some issues.

Here are some examples, please review the entire table and fix:

a) strange characters at the end of some descriptions: `station code doesn't match [A-Za-z0-9*?]{1`, what is the `{1` part for?

b) Typos like: `callibration`

c) Rule 210: `210 │ elevation XXXXXXX`.  I have no idea what this rule does.

d) Rule 309L ` 309 │ ${validatedValue} does not match: Instrument azimuth '.   I have no idea what this does either.  Also, `${validatedValue}` is confusing, just say what it is.

e) these two do not make sense, what are the tests?, there must be more to them:
`405 │ If the Channel sample rate is 0 (non-timeseries ASCII channel)`
`406 │ If the Channel sample rate is nonzero `.

f) A whole bunch of `${validatedValue.name}` usage, not sure what that is but it should be replaced with real words.

Please go through the whole table, one by one, and make sure each entry is easily understandable and fix the descriptions if needed.  Obviously these should be checked with the relevant code to make sure they do what they say.

**Comment by yazan-iris** [comment]
The printing itself is cleaned up.  We still need to finalize the rules list.
