### ISSUE TITLE
rule 321 print current units also

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-validator#110]
For M channels will be addressed by #96 but really helpful to print what the units currently are in addition to what they should be. For example:
`321,Warning,CO,CSB,VMW,00,2019-04-11T14:49:30,2019-08-01T17:40:00,Instument code M should have stage 1 input units similar to *m/s*`
would be nice to print:
`321,Warning,CO,CSB,VMW,00,2019-04-11T14:49:30,2019-08-01T17:40:00,Instument code M should have stage 1 input units similar to *m/s* but was m/s**2`

Also, small thing, but `Instument` needs an R

**Comment by timronan** [comment]
This issue is addressed by commit 50dcce59e048c84f032653023b55d4b950cd63a6 and can be tested using [stationxml-validator-1.7.0-RC-04-SNAPSHOT](https://github.com/iris-edu/stationxml-validator/releases/tag/stationxml-validator-1.7.0-RC-04-SNAPSHOT). Please download the release and test.
