### ISSUE TITLE
Some SOH channels do not have an azimuth and dip - it should not be required

### ISSUE THREAD

**Issue by SCEDC** [iris-edu/stationxml-validator#111]
The validator is flagging these SOH channels because they don't have an azimuth and zip.

GLO - GNSS longitude
GLA - GNSS latitude
GNS - GNSS number of satellites used

But azimuth and dip are not relevant to these channels.

**Comment by chad-iris** [comment]
Those channels appear not use SEED channel naming, but instead so kind of mnemonic.  In SEED and StationXML the `L` instrument code means "Low Gain Seismometer" and the `N` means "Accelerometer", which are reasonably expected to have an azimuth and dip.  Further the `G` band code means a sample rate >= 1000 to < 5000 Hertz.

I'll let others consider if there might be alternate ways to treat these in the validator, but note that such channels are easily confused for having other, well known, characteristics than these data.

**Comment by timronan** [comment]
The plan is to add GLO, GLA, GNS channel codes to the list of SOH channels in validation rule restriction C1. We will also add restrictions C1 and C2 to rule 320.  This way rule 320 will never trigger on these specific channel codes or Channel:Type == "HEALTH", "FLAG", "MAINTENANCE".

**Comment by timronan** [comment]
These channel names are already in restriction [C1](https://github.com/iris-edu/StationXML-Validator/wiki/Restrictions#channel). So I just need to add the restriction to rule 320.

**Comment by timronan** [comment]
Rule 320 has been updated to include restrictions C1 and C2.  
GLO - GNSS longitude
GLA - GNSS latitude
GNS - GNSS number of satellites used

Are all covered in restriction C1. The metadata will now pass. [Stationxml-validator-1.7.1](https://github.com/iris-edu/stationxml-validator/releases/tag/stationxml-validator-1.7.1) is now available.  Please close this issue when satisfied.

**Comment by SCEDC** [comment]
The station in question now passes validation.  Thanks for addressing it so quickly. - Ellen
