### ISSUE TITLE
Condition 403 test case failing

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-validator#114]
The error message below is given when attempting to run 'mvn package'

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   Condition403Test.fail:46 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 146, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.354 s
[INFO] Finished at: 2020-08-03T12:46:55-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project stationxml-validator: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jholland/dev/stationxml-validator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by timronan** [comment]
Sorry, I forgot to push an updated test. Can you please try to compile again?

**Comment by jholland-usgs** [comment]
Works now, thank you.
