### ISSUE TITLE
clarify multiplication, space vs *

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-validator#119]
It is not clear from the units wiki page as to how units with multiplication are encoded. Division is `/` and exponent is `**`,  but is multiplication a space or a `*`?

In SI units, space usually indicates multiply, like a newton being `kg m/s**2`, but the only example in the page shows `hit/(cm**2*hour)` seemingly indicating the `*` is needed.

`kg m/s**2` seems more natural to me than `kg*m/s**2` but either way is ok. Consistency is more important than either.

Would be nice to add a line to the list clarifying, and perhaps add newton, `kg m/s**2` to the units so there is an example.

**Comment by timronan** [comment]
The units name table has been updated to include

> Multiplication is specified using * while division is specified with / E.g. hit/(cm**2*hour).

Does this satisfactorily close this pull request?
