### ISSUE TITLE
channel depth rule

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#12]
Rule 210 Station elevation must be equal to or above Channel elevation
may not be true always, ex array in steep terrain where surface sensor is uphill from station location, or sensor is strong motion several floors up in a building.

A better check might be to compare channel elevation plus channel depth to station elevation. They might not match in all cases, but for simple stations, especially where channel lat lon is same as station, the chan elevation plus the depth of overburden should be station elevation.

**Comment by rcasey-iris** [comment]
I agree that this seems to be a suspect test.  I think we are going to leave it in place and see if there was a metadata entry that violates this check so we can see an actual example that demonstrates this is not a good rule.  The question then would be, what would be a reasonable difference?  We are also proposing going with WARNINGS vs ERRORS, so when any mismatch occurs, we could just post a WARNING about the discrepancy, but not treat it as a showstopper.

**Comment by timronan** [comment]
This rule, 210, has been addressed. Rule 210 allows a tolerance > +/- 1 km between station and channel elevations as is suggested in the SEED Manual pg. 68.
