### ISSUE TITLE
Station lat,lon rule disallow 0,0

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#13]
Add to rule to disallow if both are zero. This has happened more than once in the past. Maybe someday they will install an OBS at 0,0 but for now that probably means somebody forgot to type in a value and the system default was 0.

**Comment by metempleton** [comment]
Maybe - II.KWAJ (on an atoll) is 0.0, 0.0.  I need to ask Pete whether it really 
is at sea level before it gets to the point of having a rule, but it’s not out of the 
question…

**Comment by crotwell** [comment]
Think you have found one this would prevent, KWAJ is in the Pacific but (0, 0) is in the Atlantic off Africa, so if it has lat,lon 0,0 it is wrong.

**Comment by metempleton** [comment]
My mistake - I had just been reading the email about channel depth and thought 
this was regarding elevation & depth.  I agree that lat,long = 0,0 should get flagged.

**Comment by crotwell** [comment]
NC.IRG is an example in the current DMC database.

**Comment by chad-iris** [comment]
Agreed, new rules to disallow latititude, longitude of 0,0 for both stations and channels.

If a station ever does end up there we an hard-code the identifiers as an exception.

**Comment by yazan-iris** [comment]
Check: GeoLocationValidator
