### ISSUE TITLE
304,Error,BV,SOEH,EHE,00,2021-04-15T20:00:00,,expected equipment/sensor but was null

### ISSUE THREAD

**Issue by tonino0013** [iris-edu/stationxml-validator#132]
Dear all,

I have applied the `stationxml-seed-converter-2.1.0.jar` to convert my SEED dataless to XML format, then I use `stationxml-validator-1.7.1.jar` however i found an error that says:
 
`304,Error,BV,SOEH,EHE,00,2021-04-15T20:00:00,,expected equipment/sensor but was null`

Inside my XML file I have the following information 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.1">
  <Source>IRIS-DMC</Source>
  <Module>IRIS converter | version: </Module>
  <ModuleURI>https://seiscode.iris.washington.edu/projects/stationxml-converter/wiki</ModuleURI>
  <Created>2021-04-15T20:00:00.00Z</Created>
  <Network code="BV" startDate="2021-04-15T20:00:00Z">
    <Description>Raspberry Shake 3D, 5 Hz, Unity V/M/S</Description>
    <Station code="SOEH" startDate="2021-04-15T20:00:00Z">
      <Latitude datum="WGS84" unit="DEGREES">-16.400</Latitude>
      <Longitude datum="WGS84" unit="DEGREES">-68.006</Longitude>
      <Elevation>4613.0</Elevation>
      <Site>
        <Name>Hampaturi</Name>
      </Site>
```
I assume the Description field gives the information about the equipment / sensor, looking the `Please clarify Rule 304 #91`  seems that the conversion I did is ok.

Would you mind please give me some feedback
Thank you in advance

**Comment by rcasey-iris** [comment]
Hi Gonzalo-

	The Description field you specified is the description of the network, so here you would want to describe network 'BV' by its name and/or institution.

	The Instrument description that you want to specify is placed within each Channel.  The pattern would be something like:


<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.1">
  <Source>IRIS-DMC</Source>
  <Module>IRIS converter | version: </Module>
  <ModuleURI>https://seiscode.iris.washington.edu/projects/stationxml-converter/wiki</ModuleURI>
  <Created>2021-04-15T20:00:00.00Z</Created>
  <Network code="BV" startDate="2021-04-15T20:00:00Z">
    <Description>This is the BV network</Description>
    <Station code="SOEH" startDate="2021-04-15T20:00:00Z">
      <Latitude datum="WGS84" unit="DEGREES">-16.400</Latitude>
      <Longitude datum="WGS84" unit="DEGREES">-68.006</Longitude>
      <Elevation>4613.0</Elevation>
      <Site>
        <Name>Hampaturi</Name>
      </Site>
   <Channel code="EHE" locationCode="00" startDate="2021-04-15T20:00:00Z">
     <Latitude>-16.400</Latitude>
     <Longitude>-68.006</Longitude>
     <Elevation>4613.0</Elevation>
     <Depth>0</Depth>
     <Azimuth>90</Azimuth>
     <Dip>0</Dip>
     <Type>CONTINUOUS</Type>
     <Type>GEOPHYSICAL</Type>
     <SampleRate>5.0</SampleRate>
     <ClockDrift>0E00</ClockDrift>
     <Sensor>
         <Description>Raspberry Shake 3D, 5 Hz, Unity V/M/S</Description>
     </Sensor>


	I do not know why the stationxml-seed-converter placed the instrument description where it did, unless there was an error in the dictionary lookup within the dataless.  It could be a bug or it could be an incorrectly formatted dataless.

	-Rob

**Comment by tonino0013** [comment]
Hi @rcasey-iris,
Thanks for the time, I modified as you mentioned, however I got this error:


```
XML Document does not comply with the FDSN-StationXML xsd schema. 
Error occurs in the StationXML Document and is described by the line below (refer to trace for line #):
[2021-04-21 16:52:06] [SEVERE] edu.iris.dmc.Application exitWithError: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 30; columnNumber: 27; cvc-complex-type.2.4.a: Invalid content was found starting with element 'CalibrationUnits'. One of '{"http://www.fdsn.org/xml/station/1":PreAmplifier, "http://www.fdsn.org/xml/station/1":DataLogger, "http://www.fdsn.org/xml/station/1":Equipment, "http://www.fdsn.org/xml/station/1":Response}' is expected.]edu.iris.dmc.DocumentMarshaller.unmarshal(DocumentMarshaller.java:39)
edu.iris.dmc.DocumentMarshaller.unmarshal(DocumentMarshaller.java:27)
edu.iris.dmc.Application.read(Application.java:205)
edu.iris.dmc.Application.run(Application.java:178)
edu.iris.dmc.Application.run(Application.java:168)
edu.iris.dmc.Application.run(Application.java:147)
edu.iris.dmc.Application.main(Application.java:118)
nulljavax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:578)
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:264)
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
edu.iris.dmc.DocumentMarshaller.unmarshal(DocumentMarshaller.java:34)
edu.iris.dmc.DocumentMarshaller.unmarshal(DocumentMarshaller.java:27)
edu.iris.dmc.Application.read(Application.java:205)
edu.iris.dmc.Application.run(Application.java:178)
edu.iris.dmc.Application.run(Application.java:168)
edu.iris.dmc.Application.run(Application.java:147)
edu.iris.dmc.Application.main(Application.java:118)


```
The provider told me the Dataless is with no problem.
The error seems to be </Sensor> (line 30) accoring to the error log, thanks for the time
[SOEH_BV.txt](https://github.com/iris-edu/stationxml-validator/files/6353958/SOEH_BV.txt)

**Comment by rcasey-iris** [comment]
Hi Gonzalo-

	I'm not sure of the issue here yet.  The only difference I see is that that <Sensor> comes before <CalibrationUnits> in the output, but I shouldn't think that this ordering would make a difference.  I've reached out to the developer on this one.

	-Rob

**Comment by yazan-iris** [comment]
Hi Gonzalo

How did you generate the xml attached?  The problem seems to be with ordering the equipment (sensor/etc) before the CallibrationUnits.  A little background would be helpful, for example did the convertor generate the xml?  How does the seed looks like?

Thanks

Yazan

**Comment by tonino0013** [comment]
hi @yazan-iris and @rcasey-iris  thank you for the time.

I have a RaspberryShake sensor, so the dataless is downloaded from:
[](https://manual.raspberryshake.org/metadata.html#raspberry-shake-rs3d)
The version I have is dataless Seed V5. Then I applied the [](https://github.com/iris-edu/stationxml-seed-converter), I am using the version 2.1.0. I work with Ubuntu 16.04.
I was able to get XML file output and then I just edited with text editor the network code, station names and the dates, this is because we would like to share data to IRIS and then to world. Just in case I add the dataless file.

[SOEH_.dataless-new.zip](https://github.com/iris-edu/stationxml-validator/files/6354806/SOEH_.dataless-new.zip)
  
Thanks for the time

**Comment by yazan-iris** [comment]
So you were editing the file manually to add the sensor as the dateless does not have any sensor information.  Try this:



<CalibrationUnits>
 <Name>V</Name>
 <Description>EMF in Volts</Description>
 </CalibrationUnits>
 <Sensor>
 <Description>Raspberry Shake 3D, 5 Hz, Unity V/M/S</Description>
 </Sensor>
 <Response>

In place of

 <Sensor>
 <Description>Raspberry Shake 3D, 5 Hz, Unity V/M/S</Description>
 </Sensor>
<CalibrationUnits>
 <Name>V</Name>
 <Description>EMF in Volts</Description>
 </CalibrationUnits>
 <Response>

The xml schema insist on this order.

Yazan

**Comment by tonino0013** [comment]
Dear @yazan-iris  and @rcasey-iris ,
Works, it was the order of the <sensor> line. thank you for the time spent on this.
Stay safe and best regards
