### ISSUE TITLE
check channel dip -90 to 90

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#14]
Similar to azimuth check, dip should be -90 to 90.

Would also be really nice to correlate this with channel orientation code. So BHZ should have dip near -90. BHE should be near azimuth 90 and BHN should be near azimuth 0. I think seed tolerance is +- 5 deg?

There is the case of channels that are 180 off that may be ok (reversed polarity).

**Comment by chad-iris** [comment]
Agreed, we need a rule to check dip validity.

A different rule could check for channel orientations within the 5 deg tolerance and issue a warning if they are not good.

**Comment by yazan-iris** [comment]
see issue #27
