### ISSUE TITLE
confusing rule 402

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#15]
402 The element of a stage must match the element of the preceding stage, except for stages 0 or 1.
 Not sure what this means.

 Does this mean check for output unit of prev stage matching input unit of next stage. That would be useful, but this message is confusing.

**Comment by crotwell** [comment]
Also, I do not think there should ever be stage 0 in stationxml. What was stage zero in SEED is now the InstrumentSensitivity in stationxml.

**Comment by chad-iris** [comment]
Agreed, something is missing from the rule description.
