### ISSUE TITLE
rule 408 confusing

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#17]
408 The value of Channel::SampleRate must be equal to the value of Decimation::InputSampleRate divided by Decimation::Factor of the final response stage.

This is confusing, think you mean sample rate is input sample rate from first digital stage divided by decimation factors from each stage, not just the final stage?

**Comment by chad-iris** [comment]
It is written correctly to check on agreement of the final sample rate(s) because they are effectively documented multiple places.

There could be another rule to check that the cascade of sample rates through the stages is consistent.
