### ISSUE TITLE
add unit check on rule 409, digital output should be COUNT

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#18]
Maybe as part of rule 409, output of any "digital" stage should be COUNT.

**Comment by chad-iris** [comment]
I'm not sure that is always true.  Admittedly I can't think of any examples off hand, but there could be descriptions of data in real units (degC, Pa, etc.) that get filtered for downsampling and then produce the same units.

**Comment by rcasey-iris** [comment]
Perhaps make this a WARNING.  Not sure of the practicality of this check, but we can just flag it.

**Comment by timronan** [comment]
This warning has not been taken into account. We feel as though the 400 level test adequately test digital stages and unit names. Refer to rules 402, 403, 404 on the [Validation test](https://github.com/iris-edu/StationXML-Validator/wiki/Validation-tests) table.
