### ISSUE TITLE
check overall gain as product of stage gains

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#19]
Overall gain in InstrumentSensitivity should be product of all the stage gains IF Frequency values are same in all stages. Not sure if it would be an error if not, but all stages probably should use the same frequency value if possible.

**Comment by chad-iris** [comment]
Agreed, the test should be as you state.

Perhaps a warning if the stages do not have the same frequency values.

**Comment by metempleton** [comment]
Just  a note - datalesses drawing from NRL responses will generate many warnings 
per epoch each time.

**Comment by crotwell** [comment]
Might be too time consuming, but running the whole response through jevalresp and seeing if the output is within a tolerance of the stated value would take care of the frequency issue. Running the response through jevalresp would a good validation check on its own.

**Comment by rcasey-iris** [comment]
How about:  Check the overall gain, compare to sensitivity.  Throw ERROR if they do not agree.   Check the frequency of gain for all elements in the stack.  Throw WARNING if they do not agree.  It may be that all of the frequencies are in the flat passband, but just not exact.  Like crotwell says, a visual review of the response curve can help resolve this.

**Comment by timronan** [comment]
This guideline has been addressed by rule 412. 
Refer to: [https://github.com/iris-edu/StationXML-Validator/wiki/Validation-tests](https://github.com/iris-edu/StationXML-Validator/wiki/Validation-tests).

**Comment by timronan** [comment]
Refer to rule [412](https://github.com/iris-edu/StationXML-Validator/blob/master/Validator_TestSuite/Response_400/F1_412.xml) on the [Validation test](https://github.com/iris-edu/StationXML-Validator/wiki/Validation-tests) table.
