### ISSUE TITLE
rule 311 should allow type, manufacturer, model instead of just description

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#21]
311 Channel sensor description cannot be null/empty

One of my channels has this, which I think is much better than a simple description element.

<fsx:Sensor><fsx:Type>NANOMETRICS:TRILLIUM 120 BOREHOLE:001009</fsx:Type><fsx:Manufacturer>NANOMETRICS</fsx:Manufacturer><fsx:Model>TRILLIUM 120 BOREHOLE</fsx:Model><fsx:SerialNumber>001009</fsx:SerialNumber><fsx:CalibrationDate>1900-01-01T00:00:00Z</fsx:CalibrationDate></fsx:Sensor>

**Comment by chad-iris** [comment]
Sure that's better in terms of information content and defintion.  But we are in, and will be for some time, a transition from dataless SEED to StationXML.  In dataless there is only a single string to identify an "instrument".  We'll be translating back and forth between these formats for a while.  Furthermore it is reasonable that there is a single place to look for a description of a sensor.  We've decided that place is Description.

I suggest putting that Sensor::Type content into Sensor::Description.  It is redundant information anyway and you are using it the same way we (and others) are using Description.

**Comment by crotwell** [comment]
It is reasonable when going dataless to stationxml to put the string in description, but it seems unreasonable to me to force metadata that originates as stationxml to only use description. In particular, SIS (which will probably become a significant source of metadata) knows lots about the hardware, and so tries to populate the StationXML parameters as fully as possible. What you seems to be saying is that all those other fields in StationXML should not be used. Why bother having them in Station XML at all if they are not allowed to be used?

**Comment by chad-iris** [comment]
There must be some misunderstanding.  This rule in no way forces the use of only description and in no way implies that all those other fields should not be used.  According to the schema, all of the descriptive fields for Equipment, potentially leaving us with no descriptors at all.  This rule means there is a bare minimum of a sensor description, add all the other stuff you want.

By the way, "NANOMETRICS:TRILLIUM 120 BOREHOLE:001009" sounds much more like a sensor description to me than a type.  The type is more like "borehole seismometer" I would think.  But it's a new field without a strict definition and no precedent so kinda the wild west.

**Comment by crotwell** [comment]
Let me try for a better example, suppose I am creating StationXML for a channel, and I know that it is a Nanometrics Trillium 120PA with serial number 001623. There are (at least) three ways I can put that information into the StationXML Sensor element.

The first is what this rule seems to require:
```
<fsx:Sensor>
    <fsx:Description>NANOMETRICS:TRILLIUM 120PA:001623</fsx:Description>
</fsx:Sensor>
```

The second uses the most specific element for each type of information:
```
<fsx:Sensor>
    <fsx:Manufacturer>NANOMETRICS</fsx:Manufacturer>
    <fsx:Model>TRILLIUM 120PA</fsx:Model>
    <fsx:SerialNumber>001623</fsx:SerialNumber>
</fsx:Sensor>
```

And then there is a third case that combines both, satisfying the rule but being redundant:
```
<fsx:Sensor>
    <fsx:Description>NANOMETRICS:TRILLIUM 120PA:001623</fsx:Description>
    <fsx:Manufacturer>NANOMETRICS</fsx:Manufacturer>
    <fsx:Model>TRILLIUM 120PA</fsx:Model>
    <fsx:SerialNumber>001623</fsx:SerialNumber>
</fsx:Sensor>
```

I prefer the second, which this rule disallows. I understand that if all you have is a single string, ie convert from dataless, then it goes in description. It also makes sense to require something about the sensor. And having the same data in two places means you will eventually run into a case where they are not the same, in which case it isn't redundant, it is choose which one to believe.

I feel that using the most specific fields, and only the most specific fields, should be encouraged, rather than discouraged. Perhaps the rule should be that the sensor element cannot be empty.

**Comment by crotwell** [comment]
Just one more thought, the IRIS stationXML to dataless converter, at least the version currently used by SIS, uses the <type> element for this. So the validator and the converter may not be in sync as well.
