### ISSUE TITLE
prefer SI units with SI approved capitalization

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#23]
Although SEED has historically used all caps and says that units are case insensitive, but case matters in SI. For example "s" is second but "S" is siemen, and "mV" is millivolt, "MV" is megavolt. 

To the extent possible, stationxml should probably use the SI unit standards, including preferring the SI capitalization.

**Comment by chad-iris** [comment]
Agreed.  The list of units to be verified by the Validator has been updated:
https://github.com/iris-edu/StationXML-Validator/wiki/Unit-name-overview-for-IRIS-StationXML-validator.

**Comment by yazan-iris** [comment]
done
