### ISSUE TITLE
make dates UTC

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#25]
Dates for start/end times are printed out in local time, which is not ideal. All start/end times for net, sta, chan should be printed UTC.

Also, the full "day of week" format, like "Mon Jan 25 14:30:00 EST 2016" is verbose and harder to check. I would prefer all ISO8601 time outputs, which would match the time items later in the output.

Example:
CO_CSB.xml|406|[Channel [code=VKI, locationCode=00, startDate=Mon Jan 25 14:30:00 EST 2016, endDate=Thu Feb 11 18:00:00 EST 2016]] If Channel sample rate > 0, at least one stage must be included and be comprised of units, gain, and sample rate.|CO|||CSB|2009-04-13T00:00:00||00|VKI|2016-01-25T19:30:00|2016-02-11T23:00:00

**Comment by chad-iris** [comment]
I agree that all dates should be printed as ISO 8601 format, specifically this one:

**YYYY-MM-DDTHH:MM:SSZ**

**Comment by yazan-iris** [comment]
This was a toString default that should have not displayed in the first place, removed from output now.
