### ISSUE TITLE
New rule to test that the cascade of sample rates through the Stages is consistent

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#26]
A new rule is needed for response level: "Sample rates are consistent through cascade of Stage entries".

The check is, when a Stage::Decimation is present the Decimation::InputSampleRate value should be the same as the Decimation::InputSampleRate divided by the Decimation::Factor from the **previous** Stage.

Mentioned in #17

**Comment by yazan-iris** [comment]
Added new rule: response.stage.decimation.414
