### ISSUE TITLE
New rule to check that channel orientation codes match documented orientation

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#27]
**This rule only emits a warning, not a failure**

A new rule that checks the orientation code in the channel (e.g. E,N,Z) against the channel's azimuth and dip values.

The test should be "within 5 degrees" of the values listed in the SEED manual:

Z — Dip -90, Azimuth 0 
N — Dip 0, Azimuth 0
E — Dip 0, Azimuth 90

**Comment by metempleton** [comment]
Just a note that the GSN and ANSS datalesses will generate many warnings 
each time.  They use (12Z} regardless of orientation.

**Comment by yazan-iris** [comment]
Check OrientationValidator, this should match  Appendix A: Channel Naming in the Seed manual
