### ISSUE TITLE
Change unit value checking with updates and check both case sensitively and insenitively

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#28]
Update the units checked from the table here:
https://github.com/iris-edu/StationXML-Validator/wiki/Unit-name-overview-for-IRIS-StationXML-validator

Also, check the unit names and issue both warnings and errors.

It is an error if the unit name is **not** found in our list with a **case insensitive** comparison.

It is a warning if the unit name  **is** found in our list with a **case insensitive** comparison but not a **case sensitive** search.

**Comment by yazan-iris** [comment]
This is addressed in issue #29
