### ISSUE TITLE
Clear message when validation was successful (all tests passed)

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#3]
The command line tool should print a clear message, perhaps "Validation successful, all tests passed", when the validation was successful.

Currently, the headers for a list of failures is the only thing printed.  They should not be printed when there are no failures.

**Comment by rtweekly-iris** [comment]
If the XML is not validated by the schema, then no validation checks are performed, so the "all clear" message should probably be avoided for invalid XML.

$ java -jar validation-client-2016-07-28T223335Z.jar ../../tests/101_netcode_notnull.xml 
 Line number: 9 Column number: 97 Message: cvc-complex-type.4: Attribute 'code' must appear on element 'Network'.
JAXB unmarshalling exception; nested exception is javax.xml.bind.UnmarshalException - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 97; cvc-complex-type.4: Attribute 'code' must appear on element 'Network'.]
**Validation successful, all tests passed**
