### ISSUE TITLE
reduntant notation ** for powers of units

### ISSUE THREAD

**Issue by crotwell** [iris-edu/StationXML-Validator#32]
The [current unit naming wiki page](https://github.com/iris-edu/StationXML-Validator/wiki/Unit-name-overview-for-IRIS-StationXML-validator) says:
```
Exponents for powers are specified with **, e.g. "s**2".
```
but the ** is I think redundant as there can be no other meaning for an integer within the unit name than exponent. So would be simpler to encode power as a simple number following a unit. So acceleration would be either "m s-2" or "m/s2".

This standard may be useful as it explicitly deals with conveying units within ascii:
[http://unitsofmeasure.org/ucum.html](http://unitsofmeasure.org/ucum.html)
perhaps include a link to it on the wiki page? They also use a dot between multiplied units, like "m.s-2".

**Comment by rcasey-iris** [comment]
The notation in the wiki has been standard in FORTRAN and worked its way into generally accepted representation in SEED metadata.  I'm not sure of the need to change anything in the example as it represents how we see metadata scaling by and large.  I'm not sure of the motivation to change it, either.

**Comment by crotwell** [comment]
I would prefer units to be aligned with SI standards instead of FORTRAN standards.

**Comment by chad-iris** [comment]
More important than FORTRAN is the large historical legacy of SEED, which trumps most other issues in my opinion.  The strictness on units applied by the validator is a first step and does so while allowing most historically usage to continue, which gives us some actual chance at normalizing usage.

> I would prefer units to be aligned with SI standards instead of FORTRAN standards.

I can't find where SI specifies how to represent units raised to powers in ASCII.  The UCUM mentioned earlier is OK, but not SI; it's also a little weird with some options, like "m.s-2" is not anything I would recommend over m/s\*\*2, even m/s2 is probably much more recognized.
