### ISSUE TITLE
Sample rate comparison too strict, need comparison with tolerance

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#34]
The sample rate comparison for Rule 408 is too strict and runs into the classic problem of comparing floating point values.

A suggested comparison with tolerance is as follows:

```
abs(1-sr1/sr2) < 0.0001
```

I.e. two sample rates (`sr1` and `sr2`) are considered equal if the absolute value of (1 -  sr1/sr2) is less than 0.0001.  A C macro that does this test is:

```
#define MS_ISRATETOLERABLE(A,B) (fabs (1.0 - (A / B)) < 0.0001)
```

**Comment by yazan-iris** [comment]
Fixed
