### ISSUE TITLE
Dip/Azimuth checks should test all three orientations, regardless of first failure

### ISSUE THREAD

**Issue by rcasey-iris** [iris-edu/StationXML-Validator#37]
Current rule is to treat N,E,Z orientations as being within 5 degrees of northing,easting,vertical, otherwise are required to use the 1,2,3 numbering system.  The error message should provide a hint for the numerical naming preference for orientations that fall outside of this tolerance.

**Comment by timronan** [comment]
Rule [332](https://github.com/iris-edu/StationXML-Validator/blob/master/Validator_TestSuite/Channel_300/F1_332.xml) reflects these requirements. Error message for rule 332 has been clarified in both in the error report saying "Channel:Azimuth and or Channel:Dip do not correspond, within 5 degrees of tolerance, to last digit of orthogonal Channel:Code." A GitHub documentation page "[Channel:Code Orthogonal Orientation Guidelines](https://github.com/iris-edu/StationXML-Validator/wiki/Channel:Code-Orthogonal-Orientation-Guidelines#orthogonal-orientations)" has been created.
