### ISSUE TITLE
[Develop Test] Error 405: InstrumentSensitivity Value == Product of StageGain Value at Normalization Frequency

### ISSUE THREAD

**Issue by timronan** [iris-edu/StationXML-Validator#50]
Note: Error number 405 will be reassigned. This number to temporarily help define the subject.

Create a test that compares the product of StageGain\<Value\> from stages that StageGain\<Frequency\> = InstrumentSensitivity\<Frequency\>  to the the InstrumentSensitivity\<Value\>. These values should be equal. 

EX: Code block outlining how test could be conducted. NOT TESTED.
###
```
stagegains = Vector()
count = 1
for( i in 1: length(stages)){
    if (StageGain<Frequency>[i] == InstrumentSensitivity<Frequency>){
         stagegains[count] = StageGain<Value>
         count=+
    }
}
TotalGain = product(stagegains)
if(InstrumentSensitivity<Value> != TotalGain && count == length(stages)){
    Error 405!
}
```
###

"Compare the product of the gains of each stage *at the normalization
frequency listed in stage 0*" to the instrument sensitivity gain.

Refer to: [https://github.com/iris-edu/StationXML-Validator/issues/19](https://github.com/iris-edu/StationXML-Validator/issues/19)

**Comment by metempleton** [comment]
It also needs to be required that **all** StageGain<Frequency> in the response cascade be equal to the InstrumentSensitivity<Frequency> in order for the comparison to be made.  Perhaps execute the if statement only if count=length(stages).  (Multiplying 2 of 6 StageGain Values that satisfy the Frequency equivalence, for example, would never equal the total InstrumentSensitivity Value.)

**Comment by timronan** [comment]
Test: 405 (Future 412)  **InstrumentSensitivity:Value != Product(StageGain:Value) at Normalization Frequency**  has been developed and tested. The test compares InstrumentSensitivity:Value and Product(StageGain:Value) if if all Response:Stage:number:StageGain:Frequency are equal to Response:InstrumentSensitivity:Frequency. The test has a  threshold tolerance of 0.1%.

**Comment by timronan** [comment]
An exception needs to be made so this rule does not trigger on OCF, SOH, ACE, and LOG.

**Comment by timronan** [comment]
Refer to 412 on the [Validation Test](https://github.com/iris-edu/StationXML-Validator/wiki/Validation-tests) table.
