### ISSUE TITLE
[Develop Test] Error 407: Filters of type Digital must be composed of the elements PolesZeros|Coefficients|FIR, Decimation, and StageGain

### ISSUE THREAD

**Issue by timronan** [iris-edu/StationXML-Validator#52]
Response:Stage must be composed of the elements Response:Stage:ResponseStageType [B053-B056], Response:Stage:Decimation [B057], and Response:Stage:StageGain [B058] or Response:Stage must only include the element Response:Stage:StageGain [B058].

[B] = Blockette SEED Manual

**Comment by rcasey-iris** [comment]
This should be amended, as this only applies to digitizer stages, IIRC.  Stage 1 is generally analog in nature and does not perform any decimation on its own, so there would not be a Blockette 57 there.  In addition, this rule would not apply to non-linear response instruments utilizing a Blockette 62.  Also, and alternative for Blockette 54 is a Blockette 61, in the case of balanced FIR filters.  I can't remember if StationXML bothers with that.

	-Rob

**Comment by metempleton** [comment]
I was thinking that if there is a xTransferFunctionType, a value of DIGITAL could trigger the test. 
 
It would omit the analog stages and blockettes like 61 and 62 don’t have a TransferFunctionType.  
Polynomials are type POLYNOMIAL, so we’d also be ok there…

—Mary

**Comment by timronan** [comment]
What about this? 

[Develop Test] Error 407: A Digital Response:Stage must be composed of the elements ResponseStageType, Decimation, and StageGain

For( N 1:length(Stage)){
    %% Comment: Checks for Digital PolesZero Stages
    if(Response:Stage[N]:PolesZeros:PzTransferFunctionType:DIGITAL == TRUE && 
       Response:Stage[N]:Decimation == TRUE &&
       Response:Stage[N]:StageGain == FALSE ||
       Response:Stage[N]:PolesZeros:PzTransferFunctionType:DIGITAL == TRUE && 
       Response:Stage[N]:Decimation == FALSE &&
       Response:Stage[N]:StageGain == TRUE){
           print(Error 407)
    }
    %% Comment: Checks for Digital Coefficient Stages
    else if(Response:Stage[N]:Coefficient:CfTransferFunctionType:DIGITAL == TRUE && 
               Response:Stage[N]:Decimation == TRUE &&
               Response:Stage[N]:StageGain == FALSE ||
               Response:Stage[N]:Coefficient:CfTransferFunctionType:DIGITAL == TRUE && 
               Response:Stage[N]:Decimation == FALSE &&
               Response:Stage[N]:StageGain == TRUE){
                   print(Error 407)
    } else{}

**Comment by metempleton** [comment]
In reading further, we'll want to include the Response:Stage[N]:FIR - it will always be "digital" (so there is no field for this), so it will need Decimation & StageGain as well.  

A can of worms that we may or may not want to open is whether to include ResponseList in this test.  According to SEED, it's ok to include this as a supplement to other response descriptions, but it is not considered a valid response description standing alone.  That said, the IM network (and maybe others) commonly used ResponseList as the sole response description in the past.  When this is the case, it must also be accompanied by Decimation and Gain in order to be useful at all.  A question to the group is, do we leave this out for now, or go ahead and include it and see what kind of fallout results?

**Comment by timronan** [comment]
```
For( N 1:length(Stage)){
    %% Comment: Checks for Digital PolesZero Stages
    if(Response:Stage[N]:PolesZeros:PzTransferFunctionType:DIGITAL == TRUE && 
       Response:Stage[N]:Decimation == TRUE &&
       Response:Stage[N]:StageGain == FALSE ||
       Response:Stage[N]:PolesZeros:PzTransferFunctionType:DIGITAL == TRUE && 
       Response:Stage[N]:Decimation == FALSE &&
       Response:Stage[N]:StageGain == TRUE){
           print(Error 407)
    }
    %% Comment: Checks for Digital Coefficient Stages
    else if(Response:Stage[N]:Coefficient:CfTransferFunctionType:DIGITAL == TRUE && 
            Response:Stage[N]:Decimation == TRUE &&
            Response:Stage[N]:StageGain == FALSE ||
            Response:Stage[N]:Coefficient:CfTransferFunctionType:DIGITAL == TRUE && 
            Response:Stage[N]:Decimation == FALSE &&
            Response:Stage[N]:StageGain == TRUE){
               print(Error 407)
    }
    %% Comment: Checks for FIR
    else if(Response:Stage[N]:FIR == TRUE && 
            Response:Stage[N]:Decimation == TRUE &&
            Response:Stage[N]:StageGain == FALSE ||
            Response:Stage[N]:FIR == TRUE && 
            Response:Stage[N]:Decimation == FALSE &&
            Response:Stage[N]:StageGain == TRUE){
               print(Error 407)
    }
    } else{}
```

This could also be written as a dictionary.

**Comment by timronan** [comment]
It seems like a stand alone Response List [B055] should be rejected by the validator. 

"[55] Response List Blockette

This blockette alone is not an acceptable response description; always use this blockette along with the standard response blockettes ([53], [54], [57], or [58]). If this is the only response available, we strongly recommend that you derive the appropriate poles and zeros and include blockette 53 and blockette 58" (SEED Manual).

**Comment by metempleton** [comment]
If implemented, it should be a warning rather than an error - we have a lot of channels that will trigger this and it's not an easy fix.
