### ISSUE TITLE
[Develop Test] Error 407.5 Response:InstrumentSensitivity:Frequency < Channel:SampleRate/2

### ISSUE THREAD

**Issue by timronan** [iris-edu/StationXML-Validator#53]
Error 407.5 [Number will be changed] Response:InstrumentSensitivity:Frequency < Channel:SampleRate/2

Response:InstrumentSensitivity:Frequency must be less than the channel's Nyquist frequency (Channel:SampleRate/2).

**Comment by yazan-iris** [comment]
Currently numbered 410.

**Comment by yazan-iris** [comment]
`<SampleRate>200</SampleRate>
    <Response>
     <InstrumentSensitivity>
      <Value>1.007E9</Value>
      <Frequency>300</Frequency>
</code>`
