### ISSUE TITLE
[Develop Test] Error 430: If Stage[N]:PolesZeros[0]:Zero == TRUE than Stage[N]:StageGain:Frequency != 0  at stage N.

### ISSUE THREAD

**Issue by timronan** [iris-edu/StationXML-Validator#54]
[Develop Test] Error 430: If Response:Stage:number[N]:PolesZeros[0]:Zero == True than Response:Stage:number[N]:StageGain:Frequency != 0  at stage N. 

If there are one or more Stage[N]:PolesZeros:Zero at position 0 in Stage[N]'s cascade than Response:Stage:number[N]:StageGain:Frequency != 0  at stage N. 

A stage that contains one or more Response:Stage:number[N]:PolesZeros:Zero at position 0 cannot be normalized at 0 Hz. 

```
For( N in 1:length(Stage)){
    if(Response:Stage[N]:PolesZeros[0]:Zero == True && Response:InstrumentSensitivity:Frequency == 0){
          print("Error 430!")
    }
}
```

**Comment by metempleton** [comment]
If this is testing for a zero at zero in **any** stage, then the second part of **this** test should be whether the InstrumentSensitivity:Frequency == 0 (not the **stage** frequency).  It's my read that 430 takes care of the case where the Stage Frequency is 0.  (Unless I'm reading incorrectly...)

**Comment by timronan** [comment]
This code is testing for a zero at zero in any stage. Error 430 was written, above, to test for cases where Stage[N]:StageGain:Frequency == 0.

Error 432 will be written to test for cases where Response:InstrumentSensitivity:Frequency == 0. It seems like these need to be two separate test because Error 430 looks at frequencies in the Stage level and Error 432 looks for frequency at the Response level.

Error 430:
```
For(N in 1:length(Stage)){
    if(Response:Stage[N]:PolesZeros[0]:Zero == True && Response:Stage[N]:StageGain:Frequency == 0){
          print("Error 430!")
    }
}
```

Error 432: 
```
For(N in 1:length(Stage)){
    if(Response:Stage[N]:PolesZeros[0]:Zero == True && Response:InstrumentSensitivity:Frequency == 0){
          print("Error 432!")
    }
}
```

What do you think?
