### ISSUE TITLE
Corrupt reporting output for test failures

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#6]
This run:

    java -jar stationxml-validator-1.0.2.jar IU.ANMO.00.BHZ-BadNetandBadUnit.xml

results in:

```
file|rule-id|rule-message|network|network-start-time|network-end-time|station|station-start-time|station-end-time|location|channel-code|channel-start-time|channel-end-time
IU.ANMO.00.BHZ-BadNetandBadUnit.xml|102| network code doesn't match [A-Za-z0-9*?]{1|IUUU|1988-01-01T00:00:00|2500-12-31T23:59:59|||||||| network code doesn't match [A-Za-z0-9*?]{1
IU.ANMO.00.BHZ-BadNetandBadUnit.xml|411| Invalid input unit Meters/S for stage sensitivity|IUUU|1988-01-01T00:00:00|2500-12-31T23:59:59|ANMO|1995-07-14T00:00:00|2000-10-19T16:00:00|00|BHZ|1998-10-26T20:00:00|2000-10-19T16:00:00| Invalid input unit Meters/S for stage sensitivity
```

A number of changes should be made:

1. The "rule-message" is included again at the end of each of the messages
2. The "rule-message" for rule 102 is "network code doesn't match [A-Za-z0-9*?]{1".  What is that "{1" at the end?  Doesn't make sense.
3. The "rule-messages" start with a space and are inconsistently capitalized.  Seems like the space doesn't need to be there and each message should start with a capital letter so it reads like a message, or at least be consistent.
4. In my opinion, the header row would more obviously be a header row and readable if the field names started with capital letters, e.g. "File" instead of "file".

**Comment by chad-iris** [comment]
Test file:

[IU.ANMO.00.BHZ-BadNetandBadUnit.xml.zip](https://github.com/iris-edu/StationXML-Validator/files/360282/IU.ANMO.00.BHZ-BadNetandBadUnit.xml.zip)

**Comment by rtweekly-iris** [comment]
The debugging line "before: station code..." should be commented out.

```
$ java -jar validation-client-2016-07-28T223335Z.jar ../../tests/202_stacode_length.xml 
File|Rule-Id|Rule-Message|Network|Network-Start-Time|Network-End-Time|Station|Station-Start-Time|Station-End-Time|Location|Channel-Code|Channel-Start-Time|Channel-End-Time
before: station code doesn't match [A-Za-z0-9*?]{1,5}
202_stacode_length.xml|202|station code doesn't match [A-Za-z0-9*?]{1,5}|XX|1988-01-01T00:00:00|2500-12-31T23:59:59|TEST12|2009-07-03T00:00:00|2014-11-16T00:00:00||||
```

**Comment by rtweekly-iris** [comment]
> The "rule-message" for rule 102 is "network code doesn't match [A-Za-z0-9*?]{1". What is that "{1" at the end? Doesn't make sense.

Based on the output from the --print-rules option, the following rule-messages could be changed to be more clear and informative:
102 │ network code doesn't match [A-Za-z0-9*?]{1
202 │ station code doesn't match [A-Za-z0-9*?]{1
210 │ elevation XXXXXXX
302 │ channel code doesn't match [A-Za-z0-9*?]{1
405 │ If the Channel sample rate is 0 (non-timeseries ASCII channel) 
406 │ If the Channel sample rate is nonzero

**Comment by yazan-iris** [comment]
The new formatting is in place now.
