### ISSUE TITLE
Suggest tolerance of 5% for rule 412

### ISSUE THREAD

**Issue by metempleton** [iris-edu/StationXML-Validator#64]
evalresp complains if the product of the stage gains differ by more than 5% from the total Instrument Sensitivity.  I'd recommend this as the tolerance for rule 412.

**Comment by timronan** [comment]
This is a good suggestion. We were trying to find the correct tolerance via data stats but using a predefined standard is much better. Rule 412 has been adjusted to have a 5% tolerance.
