### ISSUE TITLE
[Error Messaging] Rule 414: stage N zero at index M is at 0; stage N StageGain:Frequency cannot be 0.

### ISSUE THREAD

**Issue by timronan** [iris-edu/StationXML-Validator#67]
Adjust the output error message for rule 414 to say

> stage N zero at index M is at 0; stage N StageGain:Frequency cannot be 0. 

Verify that rule 414 is only triggering when stage N **zero** at index M is at 0. Not when stage N **pole** at index M is at 0

**Comment by yazan-iris** [comment]
The behavior is correct
