### ISSUE TITLE
Recommend removing rule 411

### ISSUE THREAD

**Issue by metempleton** [iris-edu/StationXML-Validator#68]
I propose that we remove rule 411 from the validator:

411 | InstrumentSensitivity:Frequency must be less than Channel:SampleRate/2 [Nyquist Frequency]. 

Although responses that normalize the cascaded response curve at frequencies higher than the Nyquist typically have gain mismatches > 5% when comparing the stage 0 and calculated total gain, it is possible (but not common) choose a stage 0 gain that avoids this problem.  We don't want to reject metadata for which this is the case.  (For these responses, instrument response removal should behave predictably, although gain scaling may not.)

The most relevant test is to compare the calculated gain at the Stage 0 InstrumentFrequency with the InstrumentSensitivity, but we've agreed that doing this is beyond the scope of the validator.  We had hoped to use rule 411 to identify some of this behavior, but not all violations of 411 produce unusable responses.

**Comment by rbbbenson** [comment]
Agreed. It was discussed by DS management that if we impose this rule, the GSN would have a difficult time meeting this requirement at least.

**Comment by chad-iris** [comment]
Maybe this is a good candidate for a warning instead of an error?

**Comment by timronan** [comment]
The current version of the validator has limited warnings and we have been trying to move away from including warning messages. We may need to rethink this logic. If we create warnings we need to develop another set of warning error codes and create wiki page/table to document the warning information.

**Comment by yazan-iris** [comment]
Will introduce as a warning

**Comment by timronan** [comment]
A type column which denotes the different between an error and column was added to the SXML Validation rules.
