### ISSUE TITLE
Table printed for --print-units is the wrong list and needs other changes

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#7]
For --print-units:
1) The list is **NOT** the approved list at:
https://github.com/iris-edu/StationXML-Validator/wiki/Unit-name-overview-for-IRIS-StationXML-validator#common-unit-names

I added a date to the list on that page to provide some level of tracking.  You should put a comment the code with the date when you copied the official list into the code, so you know when it's out of date.

2) The "table" printed when --print-units is used is ~102 characters wide even though none of the unit names are even close to that length.  The default terminal width is 80 characters, so anyone that hasn't made their window >= 102 characters wide gets an ugly, hard to read table.

I'm not even sure the unit names need to be in a table, seems like unnecessary formatting.  Either get rid of the table or make it less wide (maybe match the --print-rules width for consistency).

3) Sort the the unit names.  The list is a lot easier to look for something if sorted.

**Comment by yazan-iris** [comment]
I have added a date to the printed list.  This date is coming from the units page
