### ISSUE TITLE
unknown and UNKNOWN is redundant

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-validator#77]
Having both "unknown" and "UNKNOWN" as units is redundant since the validator already makes case-insensitive matches a warning not an error. In general, I feel that the list of units should only have the preferred unit name, at least with respect to upper/lower case and let case differences be output as warnings to encourage moving to a single preferred value.

https://github.com/iris-edu/StationXML-Validator/wiki/Unit-name-overview-for-IRIS-StationXML-validator

Related https://github.com/iris-edu/stationxml-validator/issues/38 https://github.com/iris-edu/stationxml-validator/issues/28

**Comment by crotwell** [comment]
Also, missing comma between "unitless" and "unknown"

**Comment by timronan** [comment]
This has been updated in the wiki documentation and by commit fdb15a067a7a183391dfcebde982c2c9fdebe1a4.
