### ISSUE TITLE
Why is "equipment/sensor warning" produced?

### ISSUE THREAD

**Issue by jpjones76** [iris-edu/stationxml-validator#79]
The XML validator produces a warning of "expected equipment/sensor but was null" if station XML contains no node for Sensor or Equipment. However, neither Equipment nor Sensor appears to be required in https://www.fdsn.org/xml/station/fdsn-station-1.1.xsd , unless minOccurs="0" doesn't mean what I think it does. Is one of these required? If so, which? Please clarify in the warning itself if possible.

**Comment by chad-iris** [comment]
> However, neither Equipment nor Sensor appears to be required in https://www.fdsn.org/xml/station/fdsn-station-1.1.xsd , unless minOccurs="0" doesn't mean what I think it does.

This validator does more business logic checking, and is more strict than, the StationXML schema alone.  It is not possible to "encode" all of the rules that make up good StationXML within the XML Schema language.  So think of this validator as doing "schema validation plus other rules as determined by the IRIS DMC".

**Comment by jpjones76** [comment]
I'm sorry, but I don't think IRIS should require a sensor description node until the strings are standardized enough to be machine-readable. We were literally just talking on Tuesday about how that's impossible at present.
 
I object because no one knows what a given string means except (possibly) the relevant network operator(s). For example, what is "L4-XXXX=6202=J101=Ralph-XXXX" and how is that different from "L4-XXXX=McVCO=J120D=Wrmsn-XXXX"? We can't resolve that in an automated way because the next channel has "Mark L-4 1 Hz" in the same place. (these are from two UW channels, UW.VBE..EHZ and UW.VBP..EHZ, albeit at different times...they're on the same subnet and the strings are mutually unintelligible).

I know SEED Dictionaries like blockette [43] don't standardize the strings, even within the same network, but that begs the question: how does requiring a strictly descriptive string benefit either of us? 

In my case, speaking in "developer" mode for the moment, it's _not_ beneficial. Retaining the sensor description string in memory adds overhead and slows execution...but I can't use it for anything but writing station XML. So why require it?

Moreover, I can pass your validator by filling each <Description> with "Weebles wobble, but they don't fall down", or "More Than Meets the Eye". So requiring that a string be present but not checking its content seems like it only encourages non-standardized content.

**Comment by chad-iris** [comment]
> until the strings are standardized enough to be machine-readable. 

I seriously doubt that day will ever come.  The machine-readable solution is the more detailed equipment description fields in StationXML.

> I know SEED Dictionaries like blockette [43] only standardize strings within a given SEED volume, but that begs the question: how does requiring a strictly descriptive string benefit either of us?

It is the only, non-response, information required for a channel (beyond the channel code itself), making it useful as a baseline expectation.  It is extremely unlikely a creator of metadata knows _nothing_ about the sensor and is a pretty darn low-bar as a requirement.

> Retaining the sensor description string in memory adds overhead and slows execution...but I can't use it for anything but writing station XML. So why impose it?

You can choose to _not_ store it if you don't need it.

**Comment by timronan** [comment]
Also, as a side note, both "L4-XXXX=6202=J101=Ralph-XXXX" and "Mark L-4 1 Hz" are understandable. These are both Mark L4 seismometers, the latter of these is operating at 1 Hz. This information is invaluable for determining response information and making data usable/reproducible to the wider seismological community. 

[http://www.sercel.com/products/Pages/seismometers.aspx](http://www.sercel.com/products/Pages/seismometers.aspx)

**Comment by jpjones76** [comment]
> Also, as a side note, both "L4-XXXX=6202=J101=Ralph-XXXX" and "Mark L-4 1 Hz" are understandable. These are both Mark L4 seismometers, the latter of these is operating at 1 Hz.

I don't want to speak for @chad-iris here, but I think this is a good example of why he said that machine readability may never happen. A Mark L-4 (note the hyphen) can have a natural frequency of 1 Hz or 2 Hz; see http://touro.ligo-la.caltech.edu/~ospjeld/HEPI_Documentation_Website/HEPI_Main_Page/pdfs/L4.pdf

Knowing the PNSN as we both do, they probably used 1 Hz sensors in permanent sites, as they would've known by the 80s about low-frequency signals (e.g. volcanic LFEs). Is it safe to assume that every network did the same?

I can also think of no way to interpret all three strings as "Mark Products L-4 1 Hz" without false positives. The name is variously reported "L 4", "L4", and "L-4". If we regex match on `[L,l][\ -]?4`, a hypothetical string like "CMG-3T in dry well 40m deep" becomes "Mark Products L-4 1 Hz". I can't think of other geophysical products that match (Google tells me there's a guitar part and a grenade launcher), but a two-character regex is still problematic.

As another example, I've found a few permanent short-period channels in the PNW that give the sensor string as "HS-1-LT/Quanterra 330 Linear Phase Composite". If that's shorthand for "Geospace Technologies HS-1-LT geophone with Kinemetrics Quanterra Q330 digitizer", we have a different problem: AFAIK there is no "HS-1-LT". On the Geospace Technologies product website (https://www.geospace.com/sensors/), there's an HS-1, an HS-1 3C, and an OMNI-X-LT. So this string is going to match on at least two real sensors.

I wish we could standardize all of this to a table. But, as @chad-iris suggests, it would take a monumental effort to accurately update 50 years of instrumentation records.
