### ISSUE TITLE
False failure of rule 413

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#8]
Failure is reported for rule 413 even when there is no error.

**Comment by chad-iris** [comment]
Test file with .txt extension

[XX-TEST-FalseFailure-Rule413.xml.txt](https://github.com/iris-edu/StationXML-Validator/files/413843/XX-TEST-FalseFailure-Rule413.xml.txt)

**Comment by yazan-iris** [comment]
The test in question includes a check for correction > 0, now the check is for correction != 0.
