### ISSUE TITLE
StationXML version 1.1 support

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-validator#82]
When will the validator be supporting stationxml version 1.1?

Thanks

**Comment by jholland-usgs** [comment]
After further investigation of the error I was getting. It appears, the error was in a specific ordering of elements in my xml file. This was breaking the schema comparison regarding a 1.1 change.

Closing this issue

**Comment by timronan** [comment]
Thanks for solving and closing this issue.
