### ISSUE TITLE
stationXML 1.1 ? 

### ISSUE THREAD

**Issue by Pequegnat** [iris-edu/stationxml-validator#83]
Good morning,
we at RESIF have a doubt : does the station-validator handle all the stationxml 1.1 features ? Espacially those for the polynomial response ?
Best regards
Catherine Péquegnat

**Comment by timronan** [comment]
Can you please give us a specific example? This issue is too vague. Stationxml 1.1 is accepted by the loader. If you report a specific exception or bug we can address your issue. Thank you for posting.

**Comment by timronan** [comment]
This issue will be closed in 4 days if no response is provided.

**Comment by Pequegnat** [comment]
Dear Ronan, sorry for this big delay.
We have a metadata file  that fully validates against station-xml-validator-1.5.9.5.jar and that does not validate against https://www.fdsn.org/xml/station/fdsn-station-1.1.xsd

[FR.rotation.xml.gz](https://github.com/iris-edu/stationxml-validator/files/3940297/FR.rotation.xml.gz)
**Or, with just the problematics channels** : 
[rotation.xml.gz](https://github.com/iris-edu/stationxml-validator/files/3940309/rotation.xml.gz)

Thanks a lot for your comments,
best regards
Catherine

**Comment by timronan** [comment]
Hi Catherine, 
You are using an old version of the validator. The current release is 
stationxml-validator-1.6.0.2-SNAPSHOT. Please download this version of the validator from the github release page and let s know if your problem persist. Thanks for posting your issue. 

https://github.com/iris-edu/stationxml-validator/releases/tag/1.6.0.2

**Comment by Pequegnat** [comment]
Hi Tim,
In a production context we always use the last ‘stable’ release.
I’ll check and update.
Thanks for your answer.
Catherine 

Envoyé de mon iPhone

**Comment by timronan** [comment]
Hi Catherine, 

Sorry for the confusion with the pre-release tags. I changed everything on the releases page to be tagged as a pre-release. This project is still in beta. We are working on coming out with a production release soon. 

Tim
