### ISSUE TITLE
Rule 402 (unit consistency) is triggered when stage has no units

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/StationXML-Validator#9]
Rule 402, testing if InputUnit and OutputUnit entries are consistent, is triggered when a stage has no units.

Can we make this test skip stages that have no units?  The attached test file is valid concerning the units.

[XX-TEST-GainOnlyStage-UnitTestFail.xml.txt](https://github.com/iris-edu/StationXML-Validator/files/413848/XX-TEST-GainOnlyStage-UnitTestFail.xml.txt)

**Comment by yazan-iris** [comment]
This test is skipped now for stages with no units
