### ISSUE TITLE
Please clarify Rule 304

### ISSUE THREAD

**Issue by mikehagerty** [iris-edu/stationxml-validator#91]
"304 Channel:Sensor:Description cannot be null."

Maybe it should be added that Sensor:Description also cannot be empty ?

e.g., currently if you read the block below, it technically has a Description (element),
though if you were to examine the element.text, it would be an empty string (not null).

\<Sensor\>
     \<Description\>\</Description\>
\<Sensor\>

**Comment by timronan** [comment]
The validator's rule list has been updated. Please refer to http://iris-edu.github.io/stationxml-validator/tests.html or https://github.com/iris-edu/stationxml-validator/wiki/StationXML-Validation-Rule-List. During this update we developed pseudo code for many of the rules. The pseudo code is displayed in addition to the English version of the rule. To dsiplay the pseudo code  click the "Details" button on the rules list table. 

Code 304 has been updated:

> Channel:Sensor:Description must be included and assigned a string consisting of 1 <= case insensitive A-Z and numeric 0-9 characters.

Please comment for further suggestions and edits.
