### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-validator#93]
What license is this software released under?

Is it GPL V3 like the stationXML converter?

Thanks

**Comment by timronan** [comment]
Thanks for bringing this up. The stationxml-validator is to be released under GPL V3, same as the converter. I just updated the Application.java file to include the license. 

28846c2b54d16c20f70e22eee54ad224ffbf3035

**Comment by jholland-usgs** [comment]
Thanks, Is it possible to add a License.md file?

**Comment by timronan** [comment]
I just added it. Thanks for catching that.

**Comment by jholland-usgs** [comment]
Thank you very much.
I will close the ticket.
