### ISSUE TITLE
402 unit names / uppercase

### ISSUE THREAD

**Issue by megies** [iris-edu/stationxml-validator#94]
Personally, I think it is a bit weird that 402 is firing on all uppercase unit names (in my case "COUNTS"), given the fact that this used to be default with SEED and everybody has it like this usually and even the IRIS stationxml converter outputs uppercase units if they are in the dataless SEED, which they usually are.
Long story short, I think 90% of stationxmls out there will fire that warning and it will fire a gazillion times

Given this fact, I think there should be a mechanism to ignore specific warnings (like e.g. flake8 takes a list of warnings to ignore, either on command line or specified in some config file in a default location), because right now, checking my files I look at whole pages of 402 warnings and it is easy to overlook the really important warnings.

**Comment by megies** [comment]
N.b. even the official StationXML xsd schema uses all uppercase..

```
 298                     <xs:element name="ClockDrift" minOccurs="0">
 299                         <xs:annotation>
 300                             <xs:documentation>A tolerance value, measured in seconds per sample,
 301                                 used as a threshold for time error detection in data from the
 302                                 channel.</xs:documentation>
 303                         </xs:annotation>
 304                         <xs:complexType>
 305                             <xs:simpleContent>
 306                                 <xs:restriction base="fsx:FloatType">
 307                                     <xs:minInclusive value="0"/>
 308                                     <xs:attribute name="unit" type="xs:string" use="optional" fixed="SECONDS/SAMPLE"/>
 309                                 </xs:restriction>
 310                             </xs:simpleContent>
 311                         </xs:complexType>
 312                     </xs:element>
```

```
 658     <xs:complexType name="SecondType">
 659         <xs:annotation>
 660             <xs:documentation>A time value in seconds.</xs:documentation>
 661         </xs:annotation>
 662         <xs:simpleContent>
 663             <xs:restriction base="fsx:FloatType">
 664                 <xs:attribute name="unit" type="xs:string" fixed="SECONDS"/>
 665                 <xs:attributeGroup ref="fsx:uncertaintyDouble"/>
 666             </xs:restriction>
 667         </xs:simpleContent>
 668     </xs:complexType>
```
```
 669     <xs:complexType name="VoltageType">
 670         <xs:simpleContent>
 671             <xs:restriction base="fsx:FloatType">
 672                 <xs:attribute name="unit" type="xs:string" fixed="VOLTS"/>
 673                 <xs:attributeGroup ref="fsx:uncertaintyDouble"/>
 674             </xs:restriction>
 675         </xs:simpleContent>
 676     </xs:complexType>
```

[...]

**Comment by chad-iris** [comment]
Units in SEED (and flowing into StationXML) are messy, to say the least, and, in particular, non-SI.  This becomes really problematic as we continue to enter an era where units are interpreted by machines.  This happens at many stages, during selection, during processing, matching with other units of data in brokering systems, etc., etc.  The (meta)data are much more valuable the more easily interpretable the units are, which itself is easy if they conformed to conventions much broader than SEED, like SI.

We are taking the opportunity of a switch to mostly-StationXML world to nudge metadata producers in the right direction to begin to address the issues.  The "fortran" syntax is a whole other matter that we didn't touch.  The fact that the StationXML schema has upper case units has more to do with trying to make it as SEED-like as possible many years ago, ease the transition, etc. than any thought of continuing a bad convention.  Part of the strategy is to convert the obviously convertible unit symbols when possible, e.g. M/S => m/s, this will actually catch a great deal of the exiting metadata.

**Comment by megies** [comment]
I can definitely follow your reasoning, I guess what I'm trying to say is, I think it would not be a bad idea if the validator distinguished better between..
 - a *really* invalid/broken unit description (e.g. "counst") that can not be worked around by simple lower-case conversion in automated codes
 - a minor breach of case sensitivity (e.g. "COUNTS") which I would 100% work around in any automated processing tool I'd have to code, since it's no work at all and however long you wait (20 years from now?) you will still be facing the occasional legacy file that somebody did not bother to convert to best practice case sensitive units

**Comment by crotwell** [comment]
Just FYI, there is a [cleanUnitNames.py](https://github.com/crotwell/2extStationXML/blob/master/cleanUnitNames.py) python script that can help "fix" all caps units.

**Comment by timronan** [comment]
Validator 1.6.0.2 functions as described in the comment posted on 01/17/2020 by @megies.
Rule 402 is set up to throw both warnings and errors. Rule 402 triggers a warning if the unit name is contained in the validator's  Unit name List but the casing is incorrect. An error is thrown if the name is not in the list. 

- "counst" would throw an error because this unit is not contained within the unit list. 

-" COUNTS" throws a warning because this unit is contained within the unit list but the correct casing is described as "counts". 

We tried to accurately describing the function of rule 402 during the rules update done throughout late December and January. The rule reads as:

> Stage[N]:InputUnits:Name and Stage[N]:OutputUnits:Name must be assigned a value from the IRIS StationXML Unit dictionary, case inconsistencies trigger warnings.

Are there any suggestions on how to make this rule more understandable while keeping it concise? Maybe an example in a different part of the documentation could be helpful. 

Validator 1.6.0.2  has the `ignore-warnings` argument which will suppress all of the output warnings and report only errors. This is especially useful when first building stationxml documents and for larger StationXML documents. The warnings seem to be important to help users build clean and accurate StationXML documents.

Stationxml-converter 2.0.10 automatically changes unit casing when converting from dataless to stationxml. The unit conversion guidelines are outlined at:
[https://github.com/iris-edu/stationxml-seed-converter/wiki/Unit-Conversion]( https://github.com/iris-edu/stationxml-seed-converter/wiki/Unit-Conversion)

Refer to stationxml-seed-converter issue [42](https://github.com/iris-edu/stationxml-seed-converter/issues/42).

Is there a way we can improve this documentation?

**Comment by megies** [comment]
I think at least the output should not read `invalid output units COUNTS` -- which is clearly misleading in my opinion -- but something like `all upper case unit names are discouraged: 'COUNTS'`. But I still think, this will just swamp the user with non issues in the file, making it easier to overlook the actual problems. And like mentioned before, the official StationXML schema prescribes all upper case fixed units, so this feels like tilting at windmills to me.

> Validator 1.6.0.2 has the `ignore-warnings` argument which will suppress all of the output warnings and report only errors.

That might fit some people, but I would probably resort to grepping to get rid of this particular warning, after all I am interested in potential other warnings.

> Stationxml-converter 2.0.10 automatically changes unit casing when converting from dataless to stationxml

So will it convert  e.g. `unit="HERTZ"` in in `InputSampleRate` of `Decimation`? This would mean breaching the schema. Or will it leave that one intact as all upper case and just convert the other 50% of all upper case unit uses which are not explicitly mentioned in the schema? That might make a great mix of lower/upper case in one single document. :thinking: 

 ---

In any case, I just wanted to report something I personally found very odd, when trying out the validator. Mostly I was looking for something to recommend to external contacts that are supposed to ship us StationXML, because just asking for validation against the schema sadly is not enough (we regularly get StationXML files that lack channel azimuths and dips).
Anyway, I made my point and I guess this can be closed.

**Comment by crotwell** [comment]
Added an issue to stationxml spec to revise the "fixed" units in the schema so it isn't forgotten.
See:
https://github.com/FDSN/StationXML/issues/26

**Comment by timronan** [comment]
> So will it convert e.g. unit="HERTZ" in in InputSampleRate of Decimation? 

This is a good question and a legitimate concern. Decimation:InputSampleRate is a FrequencyType element which has the fix attribute of  "HERTZ". We can't changes this attributes name because it will make invalid stationxml. We only convert the casing for UnitsType.
