### ISSUE TITLE
check stage 1 input units against instrument code

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-validator#96]
Potentially useful to have a rule that the Stage 1 input units for a channel with instrument code of H or L should be m/s and for instrument code N to be m/s**2, so input units for a velocity seismometer should be velocity, and accelerometer should be acceleration?

Also apply similar to InstrumentSensitivity input units.

Similarly output units of last stage should be count.

Other instrument codes might also have similar input unit rules.

**Comment by metempleton** [comment]
Some networks used L for accelerometers before the N instrument code was added to the 
SEED channel descriptions.  Older temporary experiments would show this.  (My $.02.)

--Mary

**Comment by chad-iris** [comment]
That would disallow using centimeters, millimeters, micrometers, nanometers.  They are not common, but do we want to error-out on them?  Hmm.  It would be good to catch the expected time dimension for sure.

**Comment by crotwell** [comment]
Point take, but a rule saying BHZ should have input units of some kind of velocity, ie convertible to m/s, would be good.

For old L instrument code accelerometers, the rule could be to allow either velocity or acceleration, but would error on displacement, or temperature or...

**Comment by timronan** [comment]
This seems like these rules would be too restrictive as errors and should be potentially included as warnings. The rules could be something similar too:

| Rule ID | Description | Type |

| 406 | IF Channel:Code == ("?H?" OR "?L?") AND  (Stage[1]:InputUnit != ?m/s OR Stage[Last]:OutputUnits != count?) THEN FAIL | Warning |

| 407 | IF Channel:Code == "?N?" AND (Stage[1]:InputUnit != (?m/s OR ?m/s**2) OR Stage[Last]:OutputUnits != count?) THEN FAIL | Warning |

Are there any objections to including these?

**Comment by rcasey-iris** [comment]
Warning level notices might be okay.  The main thing is we don't want to tighten these down too much until we know just how conformant future XML authors are going to be with instrument code to units.  These are just two examples....if we start this, do we want to handle all of the units?

	-Rob

**Comment by timronan** [comment]
Should this warning be added? Have we come to a consensus?

**Comment by metempleton** [comment]
I’m ok with those warnings. (I wouldn’t be ok with errors.)

Just for background, it’s not really an error to submit a displacement response 
for a velocity transducer, or a velocity response for an accelerometer.  IM used 
to submit displacement responses for all of their instruments.  We’d _prefer_ the 
response units to match the transducer type, but it’s not an error (in my opinion) 
if it doesn’t.  (Note that a response type that doesn’t match the transducer type 
won’t show a flat passband unless the instrument is a hybrid.)

cheers,
Mary

**Comment by timronan** [comment]
Thanks Mary, I will add this rule as a warning.

**Comment by timronan** [comment]
This issue has been addressed by rule:

321: If Channel:Code[2] == (H | L | M | N) then Stage[1]:InputUnit must equal *m/s* AND Stage[Last]:OutputUnits must equal count*

Validator version [stationxml-validator-1.7.0-RC-01](https://github.com/iris-edu/stationxml-validator/releases/tag/stationxml-validator-1.7.0-RC-01), available on the Validator's releases page, includes this rule. 

Please verify this function works satisfactorily and report or close the issue based on your findings.

**Comment by metempleton** [comment]
We need to omit “M” from this - mass position input units are usually either 
V or M/S**2.  (There’s never been consensus on which description to use.)

cheers,
Mary

**Comment by timronan** [comment]
We will omit M in this next RC. Thanks for catching this.
