### ISSUE TITLE
could validator output link to rule list

### ISSUE THREAD

**Issue by SCEDC** [iris-edu/stationxml-validator#99]
It would be helpful for users to easily access git hub page describing the possible error codes by including the link to it as part of the output. - Ellen

**Comment by timronan** [comment]
Thank you for posting. We will add this enhancement into our next release. It will work by passing the validator the argument `--rules ` and the list will be printed to system out.

**Comment by timronan** [comment]
Validator version [stationxml-validator-1.7.0-RC-01](https://github.com/iris-edu/stationxml-validator/releases/tag/stationxml-validator-1.7.0-RC-01), available on the Validator's releases page, includes a flag that prints the validator rules. 

Run this command using:
java -jar stationxml-validator-1.7.0.jar --rules

The list of units accepted by the  stationxml-validator may be printed using the command:
 java -jar stationxml-validator-1.7.0.jar --units

Please verify these functions work satisfactorily and report or close the issue based on your findings.
